GET http://localhost:8081/api/v1/smartphones

###
GET http://localhost:8081/api/v1/smartphones?ids=1,3,4

###
GET http://localhost:8081/api/v1/smartphones/1

###
GET http://localhost:8081/api/v1/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJpc3MiOiJTbWFydGJ1eSIsInN1YiI6IjEiLCJleHAiOjE3NjQ0OTEzNjIsImlhdCI6MTc2NDQwNDk2Mn0.5OT2QKy7AtlJhkg4GZZc2QGnV465OrNV9nw6nUCMYXU

###
GET http://localhost:8081/api/v1/users/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsImlzcyI6IlNtYXJ0YnV5Iiwic3ViIjoiNSIsImV4cCI6MTc2NDQ4OTY1MSwiaWF0IjoxNzY0NDAzMjUxfQ.hueDu97bmrS4J0ny2SIE57cTo8yw_P-PXcp3HoYFeqw

###
POST http://localhost:8081/api/v1/signup
Content-Type: application/json

{
    "name": "",
    "email": ""
}

###
POST http://localhost:8081/api/v1/login
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "admin"
}

###

POST http://localhost:8081/api/v1/users/restore
Content-Type: application/json

{
    "email": ""
}

###
PATCH http://localhost:8081/api/v1/login
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsImlzcyI6IlNtYXJ0YnV5Iiwic3ViIjoiNSIsImV4cCI6MTc2NDQ4OTY1MSwiaWF0IjoxNzY0NDAzMjUxfQ.hueDu97bmrS4J0ny2SIE57cTo8yw_P-PXcp3HoYFeqw

###
PATCH http://localhost:8081/api/v1/users/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsImlzcyI6IlNtYXJ0YnV5Iiwic3ViIjoiNSIsImV4cCI6MTc2NDQ4OTY1MSwiaWF0IjoxNzY0NDAzMjUxfQ.hueDu97bmrS4J0ny2SIE57cTo8yw_P-PXcp3HoYFeqw

{
    "avatar": null,
    "name": "",
    "password": ""
}

###
GET http://localhost:8081/api/v1/carts/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJpc3MiOiJTbWFydGJ1eSIsInN1YiI6IjEiLCJleHAiOjE3NDI3NzUxNzMsImlhdCI6MTc0MjY4ODc3M30.KYEmpxmQE2hF15cjyR9BXp_9LHSn0hanluHVPWMkSaA

###
GET http://localhost:8081/api/v1/carts?user_id=1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJpc3MiOiJTbWFydGJ1eSIsInN1YiI6IjEiLCJleHAiOjE3NDI3NzUxNzMsImlhdCI6MTc0MjY4ODc3M30.KYEmpxmQE2hF15cjyR9BXp_9LHSn0hanluHVPWMkSaA

###
GET http://localhost:8081/api/v1/carts/1/items
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJpc3MiOiJTbWFydGJ1eSIsInN1YiI6IjEiLCJleHAiOjE3NDI3NzUxNzMsImlhdCI6MTc0MjY4ODc3M30.KYEmpxmQE2hF15cjyR9BXp_9LHSn0hanluHVPWMkSaA

###
POST http://localhost:8081/api/v1/carts/1/items
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJpc3MiOiJTbWFydGJ1eSIsInN1YiI6IjEiLCJleHAiOjE3NDI3NzUxNzMsImlhdCI6MTc0MjY4ODc3M30.KYEmpxmQE2hF15cjyR9BXp_9LHSn0hanluHVPWMkSaA

{
    "smartphone_id": 2
}

###
PATCH http://localhost:8081/api/v1/carts/1/items/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJpc3MiOiJTbWFydGJ1eSIsInN1YiI6IjEiLCJleHAiOjE3NDI3NzUxNzMsImlhdCI6MTc0MjY4ODc3M30.KYEmpxmQE2hF15cjyR9BXp_9LHSn0hanluHVPWMkSaA

{
    "quantity": 3
}

###
DELETE http://localhost:8081/api/v1/carts/1/items/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJpc3MiOiJTbWFydGJ1eSIsInN1YiI6IjEiLCJleHAiOjE3NDI3NzUxNzMsImlhdCI6MTc0MjY4ODc3M30.KYEmpxmQE2hF15cjyR9BXp_9LHSn0hanluHVPWMkSaA

###
GET http://localhost:8081/api/v1/smartphones/1/reviews

###
POST http://localhost:8081/api/v1/smartphones/1/reviews
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJpc3MiOiJTbWFydGJ1eSIsInN1YiI6IjEiLCJleHAiOjE3NDI3NzUxNzMsImlhdCI6MTc0MjY4ODc3M30.KYEmpxmQE2hF15cjyR9BXp_9LHSn0hanluHVPWMkSaA

{
    "rating": 4,
    "comment": "good"
}

###
PATCH http://localhost:8081/api/v1/smartphones/1/reviews/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJpc3MiOiJTbWFydGJ1eSIsInN1YiI6IjEiLCJleHAiOjE3NDI3MjMyMTYsImlhdCI6MTc0MjYzNjgxNn0.k0uxW4JMNkY7zkEo5Mff7dz-XYqnbXDzMqY3kOM7wpA

{
    "rating": 5,
    "comment": "greaaat"
}

###
DELETE http://localhost:8081/api/v1/smartphones/1/reviews/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJpc3MiOiJTbWFydGJ1eSIsInN1YiI6IjEiLCJleHAiOjE3NDI3NzUxNzMsImlhdCI6MTc0MjY4ODc3M30.KYEmpxmQE2hF15cjyR9BXp_9LHSn0hanluHVPWMkSaA

###